import Footer from "@/components/Footer";
import Header from "@/components/Header";
import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="h-full w-full overflow-x-hidden">
                <div className="fixed top-0 w-full z-50 ">
                    <Header />
                </div>
                {children}
                <Footer />
            </body>
        </html>
    );
}
